namespace: default
serviceName: ""

deployServer: cdns-m

replicaCount: 1

image:
  repository: ""
  name: ""
  tag: ""
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.

imagePullSecrets: {}
nameOverride: ""
fullnameOverride: ""

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
